Add grid engine credentials attribute to SLURM executor
fix the missing grid_engine_credentials bug:
spades/spades_pipeline/executors/executor_slurm.py", line 33, in join
    cmd += " " + self.grid_engine_credentials.format(QUEUE=options_storage.args.grid_queue)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Executor' object has no attribute 'grid_engine_credentials'