Changing back to stdint.h
Changing `#include <stdint.h>` to `#include <cstdint>` caused a compile error in Alpine `g++` with `musl-dev`:

```
fatal error: cstdint: No such file or directory
```